version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Installing dependencies..."
      - npm install
      - npm install -g @angular/cli@10.0.8
  build:
    commands:
      - echo "Building Angular project..."
      - ng build 
  post_build:
    commands:
      - echo "Updating files in the S3 bucket..."
      - aws s3 sync s3://codepipeline-us-east-1-588461568339/angular-pipe/SourceArti/ s3://s3://angularcicd1/ --delete